---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: wechat-payment
  name: wechat-payment
  namespace: default
spec:
  ports:
  - name: wechat-payment-port-80
    port: 80
    targetPort: 3310
    protocol: TCP
  selector:
    k8s-app: wechat-payment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: wechat-payment
  name: wechat-payment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: wechat-payment
  template:
    metadata:
      labels:
        k8s-app: wechat-payment
      name: wechat-payment
    spec:
      containers:
      - image: windsome/wechat-payment:latest
        name: wechat-payment
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /data/wechat-payment/config
      volumes:
      - name: config-volume
        configMap:
          name: wepay-cm
