export default EC => ({
  [EC.ERR_SYSTEM_ERROR]: '系统错误',
  [EC.OK]: '操作正常',
  [EC.ERR_UNAUTH]: '未登录',
  [EC.ERR_3RD_API_FAIL]: '第三方API调用失败',
  [EC.ERR_UNKNOWN]: '未知错误',
  [EC.ERR_BUSY]: '系统忙',
  [EC.ERR_PARAM_ERROR]: '参数错误',
  [EC.ERR_NO_SUCH_ENTITY]: '没有该实体',
  [EC.ERR_INSERT_DB_FAIL]: '插入数据错',
  [EC.ERR_UPDATE_DB_FAIL]: '更新数据错',
  [EC.ERR_ALREADY_EXIST]: '数据已经存在',
  [EC.ERR_MISS_REQUIRE]: '缺少必填项',
  [EC.ERR_SYSTEM_ERROR]: '系统错误',
  [EC.ERR_MODULE_NOT_INIT]: '模块没有初始化',
  [EC.ERR_NO_SUCH_API]: '没有此API',
  [EC.ERR_ARRAY_OUT_OF_INDEX]: '数组越界',
  [EC.ERR_NOT_IN_VALID_TIME]: '不在有效期内',
  [EC.ERR_NOT_ALLOW]: '不被允许的操作',
  [EC.ERR_NOT_OWNER]: '不是所有者不能操作',

  [EC.ERR_NO_CB_NOTIFY_URL]: '没有cbNotifyUrl',
});
