export default EC => ({
  [EC.ERR_SYSTEM_ERROR]: '系统错误',
  [EC.OK]: '操作正常',
  [EC.ERR_UNAUTH]: '未登录',
  [EC.ERR_3RD_API_FAIL]: '第三方API调用失败',
  [EC.ERR_UNKNOWN]: '未知错误',
  [EC.ERR_BUSY]: '系统忙',
  [EC.ERR_PARAM_ERROR]: '参数错误',
  [EC.ERR_NO_SUCH_ENTITY]: '没有该实体',
  [EC.ERR_INSERT_DB_FAIL]: '插入数据错',
  [EC.ERR_UPDATE_DB_FAIL]: '更新数据错',
  [EC.ERR_ALREADY_EXIST]: '数据已经存在',
  [EC.ERR_MISS_REQUIRE]: '缺少必填项',
  [EC.ERR_SYSTEM_ERROR]: '系统错误',
  [EC.ERR_MODULE_NOT_INIT]: '模块没有初始化',
  [EC.ERR_NO_SUCH_API]: '没有此API',
  [EC.ERR_ARRAY_OUT_OF_INDEX]: '数组越界',
  [EC.ERR_NOT_IN_VALID_TIME]: '不在有效期内',
  [EC.ERR_NOT_ALLOW]: '不被允许的操作',
  [EC.ERR_NOT_OWNER]: '不是所有者不能操作',

  [EC.ERR_USER_NO_BASEINFO]: '没有用户基本信息',
  [EC.ERR_USER_DUP_LOGIN]: '重复的用户名',
  [EC.ERR_USER_DUP_EMAIL]: '重复的邮件',
  [EC.ERR_USER_CREATE_FAIL]: '用户创建失败',
  [EC.ERR_USER_UPDATE_FAIL]: '用户更新失败',
  [EC.ERR_USER_UPD_NO_USER]: '此用户不存在，无法更新',
  [EC.ERR_USER_AUTH_NO_USER]: '用户授权失败，没有此用户',
  [EC.ERR_USER_AUTH_WRONG_PASS]: '错误的用户密码',
  [EC.ERR_USER_NO_CAP]: '用户没有权限',
  [EC.ERR_USER_NOT_LOGIN]: '用户没有登录',
  [EC.ERR_USER_DUP_VIPNUMBER]: '会员号已存在',

  [EC.ERR_TAXONOMY_DUP_TERM]: '重复的标签',
  [EC.ERR_PRICE_INDEX]: '价格不对',
  [EC.ERR_PRODUCT_PRICE_WRONG]: '价格错误',
  [EC.ERR_POST_TYPE_CHANGE_NOT_ALLOW]: '类型不能改',
  [EC.ERR_POST_MISS_REQUIRE]: '缺少必备属性',
  [EC.ERR_PRODUCT_EMPTY]: '商品不足',

  [EC.ERR_VOTE_COUNT_OVERFLOW]: '超出范围',
  [EC.ERR_VOTE_TIMEOUT]: '超出投票时间',
  [EC.ERR_VOTE_ALREADY]: '已经投票过了',
  [EC.ERR_VOTE_STATUS_WRONG]: '不在投票状态',
  [EC.ERR_VOTE_NOT_START]: '未开始投票',

  [EC.ERR_BONUS_NOT_ENOUGH]: '鲨鱼币不够',
  [EC.ERR_POINT_NOT_ENOUGH]: '鲨鱼币不够',

  [EC.ERR_USER_AUTH_SMSCODE_NONE]: '服务器验证码为空',
  [EC.ERR_USER_AUTH_SMSCODE_DIFF]: '验证码不一致',
  [EC.ERR_AUTH_ALREADY_EXIST]: '用户已经存在',
  [EC.ERR_AUTH_PHONE_MISMATCH]: '号码不一致',
  [EC.ERR_AUTH_CODE_MISMATCH]: '验证码不一致',
  [EC.ERR_AUTH_NOT_REGISTER]: '没有注册',
  [EC.ERR_AUTH_TOKEN_CHANGED]: '您在其他设备登录了',
  [EC.ERR_AUTH_WXSTATE_ILLEGAL]: '微信state不存在',
  [EC.ERR_AUTH_WXCODE_EXPIRE]: '微信code过期',
  [EC.ERR_AUTH_WX_GETUSER_FAIL]: '通过code获取微信用户信息失败',

  [EC.ERR_SEND_SMS_FAIL]: '发送短信失败',
  [EC.ERR_SEND_SMS_NO_CONTACTS]: '紧急联系人列表为空',
  [EC.ERR_SEND_SMS_LIMIT_CONTROL]: '发送短信过于频繁',
  [EC.ERR_SEND_SMS_PHONE_WRONG]: '电话号码格式不对,应为11位数字',
  [EC.ERR_AUTH_DUP_PHONE]: '电话号码已存在',

  [EC.ERR_XX_NO_SUCH_CITY]: '城市不存在',

  [EC.ERR_CHECKIN_ALREADY]: '已经打过卡了',
  [EC.ERR_CHECKIN_NOTIN]: '不在活动中或已经过期',
  [EC.ERR_CHECKIN_NOTINAREA]: '不在打卡范围',
  [EC.ERR_CHECKIN_NOGPS]: '未获得GPS位置',
  [EC.ERR_CHECKIN_WRONG_EXPIRE]: '错误的过期时间',

  [EC.ERR_ENROLL_ALREADY]: '已经报过名了',

  [EC.ERR_COMMENT_SILENT]: '已经被禁言了',

  [EC.ERR_QUESTION_STATUS_WRONG]: '错误的竞猜状态',
  [EC.ERR_QUESTION_TIME_WRONG]: '不在竞猜时间',

  [EC.ERR_CARD_WRONG_STATUS]: '卡券已经被兑换',
  [EC.ERR_CARD_WRONG_TYPE]: '错误的卡券类型',
  [EC.ERR_CARD_INVALID]: '无效卡券',
  [EC.ERR_CARD_WRONG_OWNER]: '错误的卡券拥有者',
  [EC.ERR_CARD_INVALID_TIME_RANGE]: '不在有效期范围',
  [EC.ERR_CARD_WRONG_CODE]: '兑换码错误',

  [EC.ERR_ORDER_ALREADY_PAID]: '订单已经支付完成',
  [EC.ERR_ORDER_NO_NEED_PAID]: '订单无需支付',
  [EC.ERR_ORDER_WRONG_STATUS]: '错误的订单状态',
  [EC.ERR_ORDER_STATUS_FORBID]: '订单状态不能改变',

  [EC.ERR_HEATFLOW_OVERFLOW]: '鲨气值记录超限',
  [EC.ERR_POINTFLOW_OVERFLOW]: '鲨鱼币记录超限',
  [EC.ERR_HEATFLOW_NO_RULE]: '无此鲨气值规则',
  [EC.ERR_POINTFLOW_NO_RULE]: '无此鲨鱼币规则',

  [EC.ERR_WECHAT_WRONG_PASSWORD]: '微信密码错',
  [EC.ERR_WECHAT_NO_ACCESSTOKEN]: '微信无accesstoken',
  [EC.ERR_WECHAT_NOT_IN_SESSION]: '微信用户信息未找到',
  [EC.ERR_WECHAT_MEDIA_DOWN_FAIL]: '微信媒体文件下载失败',

  [EC.ERR_WXOPEN_TICKETS_NONE]: '没有获取tickets,需要等待最多10分钟',
  [EC.ERR_WXOPEN_TICKET_WRONG]: '错误的ticket',
  [EC.ERR_WXOPEN_TOKEN_NONE]: '未获取token'
});
